#!/bin/bash
#SBATCH -D /hercules/scratch/vishnu/compact_nextflow
#SBATCH -J nf-workflow-4QnoojQH2Jr2Gc
#SBATCH -o /hercules/scratch/vishnu/compact_nextflow/nf-4QnoojQH2Jr2Gc.log
#SBATCH --no-requeue
set -e
set -o pipefail

# Input variables:
#
# - NXF_UUID: nextflow session id generated by tower
# - NXF_LOG_FILE: nextflow log file name
# - NXF_OUT_FILE: nextflow output file name
# - NXF_IGNORE_RESUME_HISTORY: do not stop for missing nextflow history file
# - NXF_CONFIG_BASE64: nextflow config file encoded as base64 string
# - NXF_SCM_BASE64: nextflow scm file encoded as base64 string
# - NXF_DEBUG: enable debugging mode
# - TOWER_ACCESS_TOKEN: Tower access token
# - TOWER_WORKFLOW_ID: Workflow ID generated by Tower
# - TOWER_CONFIG_BASE64: tower config file encoded as base64 string
# - TOWER_CONFIG_FILE: tower config file name

export NXF_IGNORE_RESUME_HISTORY=true
export NXF_WORK=/hercules/scratch/vishnu/compact_nextflow/work
export NXF_EXIT_FILE=nf-4QnoojQH2Jr2Gc.exit
export NXF_CONFIG_FILE=nf-4QnoojQH2Jr2Gc.config
export NXF_OUT_FILE=nf-4QnoojQH2Jr2Gc.txt
export NXF_ASSETS=/hercules/scratch/vishnu/compact_nextflow/work/.nextflow/pipelines/649aa9f
export NXF_UUID=54b906a4-b681-4c7f-a763-ba875220c0e1
export NXF_TML_FILE=timeline-4QnoojQH2Jr2Gc.html
export TOWER_WORKFLOW_ID=4QnoojQH2Jr2Gc
export NXF_ANSI_LOG=false
export NXF_PLUGINS_DEFAULT=nf-tower
export NXF_PRERUN_BASE64=ZXhwb3J0IFRPV0VSX0FDQ0VTU19UT0tFTj1leUpoYkdjaU9pSklVekkxTmlKOS5leUp6ZFdJaU9pSTVPREE1SWl3aWJtSm1Jam94TmprME5EUXhOamsxTENKeWIyeGxjeUk2V3lKMWMyVnlJbDBzSW1semN5STZJblJ2ZDJWeUxXRndjQ0lzSW1WNGNDSTZNVFk1TkRRME5USTVOU3dpYVdGMElqb3hOamswTkRReE5qazFmUS5VTUJNN2U2dWltTUJJY0RUbXF1Ylp6NG0tdEZwQmR5RjlEbDVIUnpSOUtrCmV4cG9ydCBUT1dFUl9SRUZSRVNIX1RPS0VOPWV5SmhiR2NpT2lKSVV6STFOaUo5LlpXWXdaVGt5WW1JdFpUVTNNaTAwTldZMUxUa3pOMlF0WVdGaE5HSTJNamN3TWpsbS5XckdxZU9wcjlsUERBTkZHM3Y0eUtfZzQ3c1gzYmJMaTlMalhkUzQwcW4wCmV4cG9ydCBOWEZfU0NNX0ZJTEU9aHR0cHM6Ly9hcGkudG93ZXIubmYvZXBoZW1lcmFsL0NsYThRcjNIV0lHUDViQnc0N2ljX0EK
export NXF_LOG_FILE=nf-4QnoojQH2Jr2Gc.log
export NXF_CONFIG_BASE64=dGltZWxpbmUuZW5hYmxlZCA9IHRydWUKdGltZWxpbmUuZmlsZSA9ICIkTlhGX1RNTF9GSUxFIgpwcm9jZXNzLmV4ZWN1dG9yID0gJ3NsdXJtJwp3b3JrRGlyID0gJy9oZXJjdWxlcy9zY3JhdGNoL3Zpc2hudS9jb21wYWN0X25leHRmbG93L3dvcmsnCg==

[[ $NXF_DEBUG ]] && (env | sort) && set -x
cache_path=".nextflow/cache/$NXF_UUID"

function save_exit() {
    # Save exit code to file: note NXF_EXIT_FILE is expected to always be set; otherwise, the script will fail (return a non-zero exit code) at this point.
    [[ $NXF_EXIT_FILE ]] && printf $1 > $NXF_EXIT_FILE
}

function pre_run() {
    if [[ $NXF_PRERUN_BASE64 ]]; then
      source /dev/stdin <<<"$(cat <(echo $NXF_PRERUN_BASE64 | base64 -d))" > >(tee -a $NXF_OUT_FILE) 2>&1
    fi
}

function post_run() {
    if [[ $NXF_POSTRUN_BASE64 ]]; then
      bash <(echo $NXF_POSTRUN_BASE64 | base64 -d) > >(tee -a $NXF_OUT_FILE) 2>&1 || true
    fi
}

function on_exit() {
    NXF_EXIT_STATUS=$?
    save_exit $NXF_EXIT_STATUS
    rm -rf $NXF_SECRETS_FILE
    export NXF_EXIT_STATUS
    post_run
    exit $NXF_EXIT_STATUS
}

function load_cache() {
    if [[ $TOWER_RESUME_DIR ]]; then
      mkdir -p "$cache_path"
      [ -e "$TOWER_RESUME_DIR/$cache_path" ] && rsync -r "$TOWER_RESUME_DIR/$cache_path"/ "$cache_path" || true
    fi
}

function term_run() {
  kill -TERM $nf_pid
  wait $nf_pid
}

trap 'save_exit $?' EXIT

pre_run
load_cache

if [[ $NXF_CONFIG_BASE64 ]]; then
  echo $NXF_CONFIG_BASE64 | base64 -d > ${NXF_CONFIG_FILE:-nextflow.config}
  unset NXF_CONFIG_BASE64
fi

# save tower config file
if [[ $TOWER_CONFIG_BASE64 ]]; then
  echo $TOWER_CONFIG_BASE64 | base64 -d > $TOWER_CONFIG_FILE
fi

# save secrets
if [[ $NXF_SECRETS_BASE64 ]]; then
  export NXF_SECRETS_FILE=$PWD/nf-${TOWER_WORKFLOW_ID}.secrets.json
  echo $NXF_SECRETS_BASE64 | base64 -d > $NXF_SECRETS_FILE
  chmod 600 $NXF_SECRETS_FILE
fi

[[ $NXF_DEBUG ]] && nextflow -Dcapsule.log=verbose info -dd

trap term_run TERM INT USR2
trap on_exit EXIT
trap '' USR1

nextflow run https\://github.com/erc-compact/compact_nextflow -name lonely_lamport -with-tower -profile hercules > >(tee -a $NXF_OUT_FILE) 2>&1 &
nf_pid=$!
wait $nf_pid
